[package]
name = "system-modeling-bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.13", features = ["dynamic_linking"] }
bevy_egui = "<0.26"
bevy-inspector-egui = "<0.24"
bevy_prototype_lyon = "0.11.0"
num-traits = "0.2.18"
bevy_eventlistener = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dependencies.bevy_mod_picking]
version = "0.18"
default-features = false
features = ["backend_egui", "backend_raycast", "backend_sprite", "debug"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[features]
default = []
init_complete_system = []