[package]
name = "system-modeling-bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.13", features = ["dynamic_linking"] }
bevy_egui = "=0.25.0"
bevy-inspector-egui = "0.23"
bevy_mod_picking = { version = "0.18", features = ["backend_egui", "backend_sprite"] }
bevy_prototype_lyon = "0.11.0"
num-traits = "0.2.18"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
